- completion.go
- root.go
- server_list.go
- Added new `hcloud completion` command
- `hcloud server delete/describe <TAB>` will now autocomplete server ids
- all commands are autocompleted
- added `--no-header` flag to `hcloud server list` for the autocomplete code
> Implement bash/zsh completion framework

- completion.go
- server.go
- server_rebuild.go
> Add server rebuild command

- CHANGES.md
- image_describe.go
- server_describe.go
- util.go
> Print dates in local time

- cli/server_create.go
The previous output was one line with one (ID) or two (ID and root password) info,
so instead of adding another one to the line, or having two lines with potentially
different amount of info, I also changed the printed output after creating a server.
It's now one short line per info: ID, IP address, optional root password.
Example:
```bash
./hcloud server create --image "ubuntu-16.04" --name "test" --type "cx11"
10s [====================================================================] 100%
Server created with ID: 920920
Root password: secret
IP address: 123.123.123.123
```
Let me know if you have any improvement suggestions
Closes #107
> Print IP address after a server was created

- cli/completion.go
The completion for all new label commands does not work.
> Fix the completion for the new label commands

- cli/completion.go
For zsh to recognize completion file when put into placehttp://zsh.sourceforge.net/Doc/Release/Completion-System.html#Autoloaded-files, the file in question needs to
include a tag `#compdef name`, [see docs](http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Autoloaded-files):
````
When compinit is run, it searches all such files accessible via
fpath/FPATH and reads the first line of each of them. This line
should contain one of the tags described below. Files whose first line
does not start with one of these tags are not considered to be part of
the completion system and will not be treated specially.
````
We stumbled upon this issue at [NixOS](https://github.com/NixOS/nixpkgs/pull/46001#issuecomment-418567160), though I would suspect more projects have this issue unless they …
> Add zsh tag

- CHANGES.md
- cli/sshkey.go
- cli/sshkey_update.go
This PR adds the missing ssh-key update command. All other resources have the update command.
> Implement missing ssh-key update

- CHANGES.md
- cli/server_ssh.go
Add -p and --port option for easily configure the port used for the ssh connection. Close #113
Also, this adds the shorthand -u for the --user flag.
> Add -p and --port option

- CHANGES.md
- cli/floatingip.go
- cli/floatingip_set_rdns.go
- cli/server.go
- cli/server_set_rdns.go
#131 and #92 
This adds a new command set-rdns for `server` and `floating-ip`. You can now easily set reverse DNS entries. 
When you do not specify an IP, as default IP we will use the ipv4 from the serve. or the address from the floating IP
> Add reverse dns commands

- CHANGES.md
- cli/server_create.go
Reading the [hcloud documentation](https://docs.hetzner.cloud/#servers-create-a-server) I found out that there is a Boolean flag, that one can send, which enables you to choose if the server should start directly after creation.
This is a good feature to include if one wants to install alternate operating systems from the default vm images provided by Hetzner Cloud.
> Add `start-after-create` flag to server create cmd

- CHANGES.md
- cli/floatingip_list.go
- cli/image_list.go
- cli/server_list.go
- cli/sshkey_list.go
- cli/util.go
- cli/volume_list.go
With this PR more optional output columns are added to the resource list commands.
`hcloud server list`
+ type
+ labels
+ volumes
+ protection
`hcloud volume list`
+ labels
+ protection
`hcloud image list`
+ labels
(protection already exists) 
`hcloud floating-ip list`
+ labels
(protection already exists) 
`hcloud ssh-key list`
+ labels
Issue: #145
> Add more optional output columns to resource list commands

- CHANGES.md
- cli/server_create.go
The option --user-data-from-file can now be used multiple times on a
"server create" command. If this option is specified more than once, all
files will be opened and put into a multipart MIME message which will
then be send to the API. The cloud-init can understand this MIME
message and unpack it.
> Allow option --user-data-from-file multiple times on "server create".

- cli/util.go
> Output of describe -o format should go to stdout

- cli/completion.go
This fixes an issue with zsh completion.
A leading newline prevents zsh completion definitions from autoloading.
See https://github.com/hetznercloud/cli/issues/177 for details.
> Remove leading newline in zsh completion

- cli/floatingip_create.go
- cli/network_create.go
- cli/server_create.go
- cli/server_create_image.go
- cli/sshkey_create.go
- cli/volume_create.go
This way, servers can be labeled at creation time.
Example usage:
```
hcloud server create \
--image=$image \
--datacenter=nbg1-dc3 \
--type=cx21 \
--label project=cloud --label stage=test \
--name=db-replica-1
```
> Add option to label servers, volumes, images, floating ips and ssh keys on creation

- cli/floatingip_list.go
- cli/image_list.go
- cli/network_list.go
- cli/server_list.go
- cli/sshkey_list.go
- cli/volume_list.go
This came out in the Hetzner Forum. A customer wanted to be able to see the creation date within the list response. It turned out that the created date is not available for this list. This MR changes this.
> Allow the created field to be within the list responses

- cli/server.go
- cli/server_request_console.go
Add command to request a VNC console. Also includes a proxy translating WebSocket to a normal TCP socket using the `-l` flag. This allows a normal VNC viewer to connect to the console by connecting to localhost:5900.
This also updates the version of the hcloud library to make use of the console API added in https://github.com/hetznercloud/hcloud-go/pull/134
Preview:
> Add command to request a VNC console

- README.md
This pull requestion updates the README, so that users of zsh and antigen can copy-paste a way to have hcloud completion working.
> added instructions for completion with antigen in zsh.

- cli/context_list.go
Closes #248 
When you run `hcloud context delete <ActiveContextName>` we set `cli.Config.ActiveContext = nil` (https://github.com/hetznercloud/cli/blob/master/cli/context_delete.go#L28). This leads in the `hcloud context list` to the problem that `cli.Config.ActiveContext`can be nil, but we try to access the `Name` (https://github.com/hetznercloud/cli/blob/master/cli/context_list.go#L60)
> Fix context list nil pointer when no active context was given.

- cli/load_balancer_type_describe.go
- cli/servertypes_describe.go
This is a way to solve #241. Showing the prices in the list endpoint might be a bit difficult as there may be different prices per location, so this adds the data to the `describe` endpoint, where it might help most of our customers if they are using the CLI.
I'm not quite sure if this is the best solution, so @thcyron and @LD250 what do you think about it?
> Add pricing per location to load-balancer-type describe and server-type describe

- .github/workflows/ci.yml
sstephenson/bats is not maintained any longer [1].
it spilled errors when running tests. replacing it with
bats-core/bats-core worked out of the box.
[1]: https://github.com/sstephenson/bats/pull/269 etc.
> Switch bats to maintained bats-core (CI)

- internal/cmd/firewall/add_rule.go
- internal/cmd/firewall/delete_rule.go
- internal/cmd/firewall/validation.go
- internal/cmd/firewall/validation_test.go
The cli normalized the given CIDRs by default, so when a user entered 10.0.0.1/8 (as a sample) the cli normalized it to 10.0.0.0/8 silent. After this MR we now validate that the given IP is the start of the CIDR block (e.g. 10.0.0.0/8).
This also includes a fix for #303
> cli normalized CIDRs silent

- internal/cmd/firewall/replace_rules.go
> Fix panic: runtime error: index out of range [0] with length 0 in firewall replace-rules

- README.md
- internal/cmd/completion/completion.go
> Add Powershell completion

- internal/cmd/firewall/delete_rule.go
As reported in hetznercloud#320, firewall rules can not be deleted because they
would not exist even if they are shown in "firewall describe".
This behaviour was correct because reflect.DeepEqual also compares if a
slice is empty or nil.
The slices DestinationIPs and SourceIPs are empty slices in an existing
firewall rule. However, the temporary FirewallRule object had slices
that were nil.
To fix this problem, the simple solution is to create an empty IPNet slice
for the respective direction (DestinationIPs for the direction "in", and
SourceIPs for the direction "out").
Signed-off-by: Tom Siewert <tom.siewert@hetzner.com>
> firewall: Add empty slices for respective direction instead of nil-slices

- internal/cmd/firewall/add_rule.go
- internal/cmd/firewall/delete_rule.go
In the last few days I have seen some customers which have issues with creating firewall rules because they do not add the port(-range) when using TCP or UDP as protocol. The error message `invalid_input` is not immediately understandable that in this case the port is missing.
> firewall: Require port for TCP and UDP and deny for ICMP

- internal/cmd/certificate/list.go
- internal/cmd/datacenter/list.go
- internal/cmd/server/list.go
The certificate, datacenter and server list command returned a twice
encoded JSON object and therefore caused a `null` output at the end of
e.g. `hcloud server list -o json`
Signed-off-by: Tom Siewert <tom@siewert.io>
> internal/cmd: Remove redundant DescribeJSON from JSONSchema

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/release_on_tag.yml
- go.mod
- go.sum
goreleaser has currently a bug with go 1.17, that prevents build on darwin/arm64. Therefore we revert those changes
> Use go 1.16 again

- README.md
I wanted to use `hcloud` on my Fedora box and I usually prefer to
install packages from distro repos - if they are reasonably recent so
even though Fedora was not listed as providing said package, I went
ahead and ran `dnf search hcloud` to, well, search for `hcloud`.
apparently, `hcloud` *is* indeed packaged[1] for Fedora.
it might help other users if they also learn about it here.
[1]: https://koji.fedoraproject.org/koji/packageinfo?packageID=35663
Signed-off-by: wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHfsettings <a_mirre@utb.cz>
> Add Fedora to the list of third-party providers

- .github/workflows/build.yml
- .goreleaser.yml
- gon.hcl
- internal/cmd/server/enable_rescue.go
> Remove freebsd64 rescue system type

- README.md
We should not recommend using third-party packages, as they might be fully outdated. We only "advertise" the official ways as of now.
> Remove Third-party packages Table

- go.mod
- go.sum
- internal/hcapi2/mock/zz_primary_ip_client_mock.go
- internal/hcapi2/mock/zz_server_client_mock.go
- internal/hcapi2/zz_primary_ip_client_base.go
- internal/hcapi2/zz_server_client_base.go
Rebased on #414 to fix the errors that occured when regenerating our mocks.
> chore: update hcloud-go to v1.37.0

- internal/cmd/primaryip/list.go
- internal/cmd/primaryip/list_test.go
Calls to `hcloud primary-ip list` would only return the first page of the results which by default is 50 items. By using `.AllWithOpts` instead of `.List`, hcloud-go automatically fetches all pages for us.
> fix: primary-ip list returns max 50 items

- internal/cmd/certificate/list.go
- internal/cmd/floatingip/list.go
- internal/cmd/image/list.go
- internal/cmd/loadbalancer/list.go
- internal/cmd/network/list.go
- internal/cmd/network/list_test.go
- internal/cmd/placementgroup/list.go
- internal/cmd/placementgroup/list_test.go
- internal/cmd/primaryip/list.go
- internal/cmd/primaryip/list_test.go
- internal/cmd/server/list.go
- internal/cmd/sshkey/list.go
- internal/cmd/util/util.go
- internal/cmd/util/util_internal_test.go
- internal/cmd/volume/list.go
As an SRE, I deploy a lot of hcloud resources automatically via the hcloud API and use the cli to validate those changes. I am deploying using immutable VMs rather than phoenix deployments (instead of updating existing VMs, I re-create them with the newest config) Since I am using the API in automation to create hcloud resources, my hcloud resources include Ids in their name, making it a mess sometimes to figure out which is the newest VM. To know which VM got deployed when, I often find myself using the hcloud-cli like this:
```bash
$ hcloud server list -s name -o 'columns=name,status,created,ipv4,ipv6'
NAME                           STATUS    CREATED                        IPV4             IPV6
cedi-dev-control-plane-xxxxx   running   Sun Nov 13 13:43:05 CET 2022   XXX.XXX.XXX.XXX …
```
> Adding an age column to the cli, closes #417

- internal/cmd/loadbalancer/create.go
- internal/cmd/network/add_subnet.go
- internal/hcapi/location.go
- internal/state/helpers.go
We previously hard-coded the available network zones for autocompletion purposes. This makes it easy to forget to add them, or only update the list in one location (as you can see, it's currently missing us-east for the loadbalancer create call).
In this PR we replace the hardcoded list with an api call that retrieves all available network zones from the API. As there is no dedicated `GET /v1/network_zones` endpoint, we use the network zone referenced in the `GET /v1/locations` response.
> feat(completion): read network zones from API

- .github/workflows/build.yml
Newer versions of goreleaser cause the `gon+ hook to fail in the `codesigning` step, causing a timeout of the release pipeline. This in turn causes the GitHub release to not have any attached assets.
See #427 and #429.
> ci: fix issue where release pipeline fails and no assets are produced

- .github/workflows/build.yml
- .goreleaser.yml
- script/decrypt_secrets.sh
By default the keychain that is used to sign macOS binaries is only unlocked for 300s. This caused the release process to fail, as building all binaries took longer than the 300s, and subsequent signing failed.
The new timeout is 3600s (1h), which should be enough to build anything we want. At the moment building all binaries takes ~8m, so we have a buffer of 52m or 650%.
Further changes made here:
- fix(ci): show logs of gon hooks
This makes debugging any issues encountered in these steps easier.
- fix(ci): use similar goreleaser settings to tagged release builds
In release builds we use `--parallelism=2` and the latest goreleaser version. We should use the same settings in our dev builds.
> fix(ci): race-condition in signing macos binaries

- internal/cmd/loadbalancer/load_balancer.go
This commit allows for the additional use of `hcloud loadbalancer list` instead of `hcloud load-balancer list`. This is just a small quality of life update, to allow for both options.
> Adding "loadbalancer" as an alias to the "load-balancer" command

- internal/cmd/primaryip/labels.go
- internal/cmd/primaryip/primaryip.go
Adds subcommands to add and remove labels from primary-ip resources.
> feat(primary-ip): add and remove labels

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Adding a .devcontainer configuration
**What this PR does / why we need it**:
If you never worked with Devcontainers before, here is a good article about it: [What the heck are devcontainers][1].
Another good one can be found here: [your open source project needs a devcontainer - here's why][2]
Tl;Dr:
Devcontainers are awesome and they help to define an isolated development environment which is standardised across all contributors setups and leverages the beauty of [GitHub Codespaces][3].
**Special notes for your reviewer**:
Just try it out once, before dismissing it.
Setting up your VScode to use the Devcontainer is easy:
1. Make sure you have the following plugin installed: [`ms-vscode-remote.remote-containers`][4]
2. Open VScode in the root-directory of the Repository
3. Click "Reopen …
> Adding a .devcontainer configuration for usage in GitHub Codespaces

- README.md
- internal/version/version.go
The text "not built properly" is factually wrong, as we do recommend building from source if no pre-built binary is available. By using "unknown" instead, we signify that the actual version is just that, unknown.
Closes #437
> fix: improve unset version specifier

- internal/state/helpers.go
When enabling debug output (`HCLOUD_DEBUG=true`), this was being printed to stdout by default. If one was using the output of the command in a script, this would break that usage.
By outputting to stderr, we can make sure that the "normal" output still works as expected and can be used in subsequent steps.
For example:
```shell
export HCLOUD_DEBUG=true
IP=$(hcloud server ip hccm-dev-1)
ping $IP
```
> fix: send debug output to stderr

- internal/cmd/server/create.go
The cli would crash when trying to create a server with a server type that did not exist in the API.
> fix: crash on server create with missing server type

- .goreleaser.yml
As we automated the release with release-please, its even easier to forget to "publish" to release AGAIN after goreleaser adds the assets.
> build: do not set release back to draft

- .github/workflows/bot_stale.yml
- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/release_on_tag.yml
These actions were using Node 12, which will be shut down on 2023-05-18: https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/
While I was in the files, I also streamlined to workflows so they are more similar to eachother and optimized the asset uploading for preview builds.
> ci: bump all actions to latest major version

- .github/workflows/release-please.yml
The default token GH_TOKEN in workflows does not trigger new events. We rely on the "tag" event created by release-please to build our release assets.
By using a token for "hcloud-bot", the event will be properly created.
We explicitly only run the workflow job if the repository is the main repo, as otherwise this workflow will fail in forks because the secret is not available.
Closes #476
> ci: fix release assets not available

- internal/cmd/base/delete.go
- internal/cmd/certificate/certificate.go
- internal/cmd/certificate/delete.go
- internal/cmd/firewall/delete.go
- internal/cmd/firewall/firewall.go
- internal/cmd/floatingip/delete.go
- internal/cmd/floatingip/floatingip.go
- internal/cmd/image/delete.go
- internal/cmd/image/image.go
- internal/cmd/loadbalancer/delete.go
- internal/cmd/loadbalancer/load_balancer.go
- internal/cmd/network/delete.go
- internal/cmd/network/network.go
- internal/cmd/placementgroup/delete.go
- internal/cmd/placementgroup/delete_test.go
- internal/cmd/placementgroup/placementgroup.go
- internal/cmd/primaryip/delete.go
- internal/cmd/primaryip/delete_test.go
- internal/cmd/primaryip/primaryip.go
- internal/cmd/server/delete.go
- internal/cmd/server/server.go
- internal/cmd/sshkey/delete.go
- internal/cmd/sshkey/sshkey.go
- internal/cmd/volume/delete.go
- internal/cmd/volume/volume.go
The `hcloud server delete` command returned before the action was actually awaited. This caused a race condition when creating new servers with the same name.
> fix(server): wait for delete before returning

- internal/cmd/network/create.go
- internal/cmd/network/describe.go
- internal/cmd/network/expose-routes-to-vswitch.go
- internal/cmd/network/list.go
- internal/cmd/network/network.go
- internal/cmd/network/update.go
Feature was released today. This adds:
- Showing the field in `network describe` (also for `-o json`)
- Setting the field through flag on `network create`
- Updating the setting through the command `network expose-routes-to-vswitch`
> feat(network): add support for exposing routes to vswitch connection

- internal/cmd/primaryip/create.go
When creating a Primary IP and directly assigning it to a server, the id was not passed on to the API. This caused the API request to error:
```shell
➜ hcloud primary-ip create --type ipv4 --name test --assignee-id 1234
hcloud: invalid input in fields 'assignee_id', 'datacenter' (invalid_input)
```
> fix(primary-ip): assignee-id was not correctly passed when creating the IP

- .gitlab-ci.yml
The CI pipeline is not running because of a missing tag.
I am moving the default GitLab pipeline config (job tags, job templates) to a shared repository.
> ci: fix gitlab pipeline not running

- internal/cmd/output/output.go
Because we changed the type of ID fields but did not update the code that reflects on the structs to also allow int64 fields.
Broken since #512
> fix(output): ID column could not be selected

- internal/cmd/volume/create.go
> feat: allow formatting a volume without automounting it

- internal/cmd/loadbalancer/add_service.go
- internal/cmd/loadbalancer/remove_target.go
Spotted a slight wording error while I was creating a load balancer. The help states `remove-target            Remove a target to a Load Balancer`. This should be `Remove a target from a Load Balancer` imo.
> docs(load_balancer): word mistake in help output

- internal/cmd/loadbalancer/list.go
- internal/cmd/loadbalancer/list_test.go
This commit adds the health status of a loadbalancer to the list command to display the loadbalancer health in a similar style as in the browser
> feat(load-balancer): Add health status to list output

- internal/cmd/primaryip/disable_protection.go
- internal/cmd/primaryip/enable_protection.go
This PR changes how enable/disable-protection works on primary IPs. You can now pass the protection level as an optional argument. This is to make it consistent with other enable/disable-protection commands.
> feat(primary-ip): enable/disable-protection accept levels as arguments

- internal/cmd/floatingip/create.go
- internal/cmd/loadbalancer/create.go
- internal/cmd/network/create.go
- internal/cmd/primaryip/create.go
- internal/cmd/server/create.go
- internal/cmd/volume/create.go
> feat: add --enable-protection flag to "create" commands

- internal/cmd/server/create_test.go
> test(server): test --enable-protection and --enable-backup in "create" command

- internal/cmd/base/list.go
- internal/cmd/certificate/certificate.go
- internal/cmd/certificate/list.go
- internal/cmd/datacenter/datacenter.go
- internal/cmd/datacenter/list.go
- internal/cmd/firewall/firewall.go
- internal/cmd/firewall/list.go
- internal/cmd/floatingip/floatingip.go
- internal/cmd/floatingip/list.go
- internal/cmd/image/image.go
- internal/cmd/image/list.go
- internal/cmd/iso/iso.go
- internal/cmd/iso/list.go
- internal/cmd/loadbalancer/list.go
- internal/cmd/loadbalancertype/list.go
- internal/cmd/location/list.go
- internal/cmd/location/location.go
- internal/cmd/network/list.go
- internal/cmd/placementgroup/list.go
- internal/cmd/primaryip/list.go
- internal/cmd/primaryip/list_test.go
- internal/cmd/primaryip/primaryip.go
- internal/cmd/server/list.go
- internal/cmd/servertype/list.go
- internal/cmd/sshkey/list.go
- internal/cmd/sshkey/sshkey.go
- internal/cmd/volume/list.go
- internal/cmd/volume/volume.go
> refactor: export list commands and only pass flags to ListCmd.Fetch

- internal/cmd/floatingip/list.go
On the FloatingIPClient List was used instead of AllWithOpts, which resulted in "list" only returning the first 50 entries. (Same as #415)
> fix(floating-ip): list command only returns first 50 entries

- internal/cmd/loadbalancer/update_service.go
This fixes the description for the `protocol` flag of the `load-balancer update-service` command. Before this change, the description was identical with the description of the `health-check-protocol` flag.
> docs(load-balancer): change description for protocol flag

- internal/cli/root.go
- internal/cmd/all/all.go
- internal/cmd/all/list.go
- internal/cmd/all/list_test.go
- internal/cmd/base/list.go
- internal/cmd/certificate/list.go
- internal/cmd/datacenter/list.go
- internal/cmd/firewall/list.go
- internal/cmd/floatingip/list.go
- internal/cmd/image/list.go
- internal/cmd/iso/list.go
- internal/cmd/loadbalancer/list.go
- internal/cmd/loadbalancertype/list.go
- internal/cmd/location/list.go
- internal/cmd/network/list.go
- internal/cmd/placementgroup/list.go
- internal/cmd/primaryip/list.go
- internal/cmd/server/list.go
- internal/cmd/servertype/list.go
- internal/cmd/sshkey/list.go
- internal/cmd/volume/list.go
> feat: add "all list" command to list all available resources

- internal/cmd/context/create.go
This fixes a bug that was introduced in #582 
Example pipeline in which the bug occured: https://github.com/hetznercloud/cli/actions/runs/6638017209/job/18033507784#step:4:57
> chore: convert syscall.Stdin to int to fix build on Windows

- internal/cmd/datacenter/list.go
- internal/cmd/loadbalancertype/list.go
- internal/cmd/location/list.go
- internal/cmd/servertype/list.go
The list commands for datacenters, load balancer types, locations and server types uses ``List()`` instead of ``AllWithOpts()`` to fetch resources. ``List()`` only returns a single page of resources at a time (50 entries in this case), while ``AllWithOpts()`` returns all of them. This does not make a difference at the moment, but could be a problem in the future.
Similar to #574
> fix: static resource list commands only return first 50 entries

- internal/cmd/certificate/describe.go
- internal/cmd/datacenter/describe.go
Removes duplicate entries, adds whitespace (newlines & tabs) where necessary
> fix: inconsistent formatting in "describe" commands

- internal/cmd/floatingip/list.go
- internal/cmd/primaryip/list.go
Since IP is a ``*hcloud.PrimaryIP``, ``AddAllowedFields()`` only adds columns for primitive types and a field function for IP was missing, you were not able to output the IP column using output flags.
Closes #591
> fix(primary-ip): list does now allow to output IP column

- .github/workflows/ci.yml
Leverage the https://github.com/hetznercloud/.github/pull/16 regex manager to update the version variables.
> ci: add renovate regex comment to version variables

- .github/workflows/release.yml
The GPG key now requires a passphrase to be imported.
> ci: use passphrase to import gpg private key

- internal/cmd/image/update.go
As described in the [API Docs](https://docs.hetzner.cloud/#images-update-an-image), the only allowed image type to update to is `snapshot`. The completions should reflect that.
> fix(image): backup is suggested as type in update command

- internal/cmd/primaryip/update.go
Due to not correctly checking if the auto-delete flag was set, every time the update command was called and the auto-delete flag wasn't set, auto deletion was erroneously disabled.
> fix(primary-ip): updating the name resets auto-delete

- internal/cmd/server/list.go
- internal/cmd/server/list_test.go
> feat(server): allow to filter list by server status

- internal/cmd/base/describe.go
- internal/cmd/certificate/describe.go
- internal/cmd/datacenter/describe.go
- internal/cmd/firewall/describe.go
- internal/cmd/floatingip/describe.go
- internal/cmd/image/describe.go
- internal/cmd/iso/describe.go
- internal/cmd/loadbalancer/describe.go
- internal/cmd/loadbalancertype/describe.go
- internal/cmd/location/describe.go
- internal/cmd/network/describe.go
- internal/cmd/placementgroup/describe.go
- internal/cmd/primaryip/describe.go
- internal/cmd/server/describe.go
- internal/cmd/servertype/describe.go
- internal/cmd/sshkey/describe.go
- internal/cmd/volume/describe.go
> fix: integer fields are displayed as floats when using describe with -o=yaml

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
In order to automatically align the Go version with the one used in development, I would suggest to prefer the `go-version-file` option of the setup action, so the Go version  does not need to be managed manually. 
PS: It might be meaningful to think of introducing a test-matrix for `.github/workflows/ci.yml`, so the officially supported Go versions are checked. If this is something you consider to do, I'm willing to file a subsequent PR for this ;)
> ci: prefer `go-version-file` option for `actions/setup-go`

- internal/cmd/base/labels.go
- internal/cmd/certificate/labels_test.go
- internal/cmd/firewall/labels_test.go
- internal/cmd/floatingip/labels_test.go
- internal/cmd/image/labels_test.go
- internal/cmd/loadbalancer/labels_test.go
- internal/cmd/network/labels_test.go
- internal/cmd/placementgroup/labels_test.go
- internal/cmd/primaryip/labels_test.go
- internal/cmd/server/labels_test.go
- internal/cmd/sshkey/labels_test.go
- internal/cmd/volume/labels_test.go
> feat: allow adding/removing multiple labels at once

- .github/workflows/ci.yml
The golangci/golangci-lint-action handle its own cache, we should not pollute it with the setup-go cache.
> ci: go cache is handled by golangci/golangci-lint-action

- internal/state/config/config.go
The config file was not read properly because `rawConfig` fields were made unexported in a previous PR (#672)
BEGIN_COMMIT_OVERRIDE
test: make state config mockable
END_COMMIT_OVERRIDE
> fix: config not read properly

- internal/cmd/server/enable_rescue.go
The `linux32` rescue type has been removed and is now unsupported ([See docs](https://docs.hetzner.cloud/changelog#2024-01-08-server-action-enable-rescue-no-longer-supports-32bit)). This PR removes it from suggestions and also checks for the passed type to be valid before sending an API request (like how it's done with other enums).
> feat(server): remove unsupported linux32 rescue type

- internal/cmd/certificate/create.go
- internal/cmd/certificate/create_test.go
- internal/cmd/certificate/testdata/managed_create_response.json
When creating a managed certificate, the complete data is only available once the related action has completed. Instead of then returning the initial response data, we now fetch the certificate and return this request's response data.
> fix: refetch after creating managed certificate

- internal/cmd/image/list.go
As of now, I had to use `-oyaml | yq` to filter out the supported types.  
It would be good to have it in the help message itself.
> docs: add available types to hcloud image list --help

- internal/cmd/firewall/delete_rule.go
- internal/cmd/firewall/delete_rule_test.go
If you try to delete last firewall rule, rule is `null` but should be `[]`, resulting in error message 
> hcloud: invalid input in field 'rules' (invalid_input)
`hcloud firewall delete-rule --direction in --protocol tcp --source-ips '8.8.8.8/32' --port 443 f2b`
> fix: removing last rule from firewall fails with invalid_input error

- internal/hcapi2/mock/mock_gen.go
This file was erroneously deleted in #672
> chore: restore mock_gen.go

- internal/cmd/server/ssh.go
- internal/cmd/server/ssh_test.go
- internal/state/config/config.go
- internal/state/config/zz_config_mock.go
- internal/testutil/cmd.go
> fix: allow passing multiple args to server ssh command

- internal/state/actions_test.go
- internal/ui/actions.go
- internal/ui/actions_test.go
- internal/ui/helpers.go
- internal/ui/progress.go
- internal/ui/progress_terminal.go
- Reduce the width of the actions messages (remove 'to complete')
- Only print progress when the terminal width is bigger than 80.
- Reduce the padding when printing the actions messages
Fixes #767
> fix: track progress if the terminal width allows it

- README.md
- internal/cmd/datacenter/describe_test.go
- internal/cmd/server/create_test.go
- internal/cmd/server/testdata/create_response.json
Learn more: https://docs.hetzner.cloud/changelog#2024-06-06-old-server-types-with-shared-intel-vcpus-are-deprecated
> chore: replace deprecated server type with cx22

- internal/cmd/servertype/list.go
- internal/cmd/servertype/list_test.go
Adds a new column to `hcloud server-type list -o=columns=deprecated` that shows the time when the resource is going to be made unavailable. This matches the current behavior in `hcloud image list`.
> feat(server-type): add deprecated column to list command

- internal/cmd/base/delete.go
- internal/cmd/util/resource.go
- internal/cmd/util/slices.go
- internal/cmd/util/slices_test.go
Closes #779 
- Delete the resources in batches of 10
- Reduce the complexity of the code by not using `goroutines`. We are already trying to limit the strain on the API by deleting in batches of 10, therefor waiting the actions of multiple delete calls is enough "concurrency" for this use case.
> feat: delete resources in batches of 10

- .github/workflows/build.yml
- .github/workflows/release.yml
- .goreleaser.yml
Fixed the warning.
```console
$ goreleaser check
• only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
• checking                                 path=.goreleaser.yml
e  • 1 configuration file(s) validated
• thanks for using goreleaser!
```
https://goreleaser.com/blog/goreleaser-v2/?h=v2#upgrading
> It should only warn you about the version header in the configuration file, which you can fix by adding version: 2 to it.
```console
$ goreleaser check                       
• checking                                 path=.goreleaser.yml
• 1 configuration file(s) validated
• thanks for using goreleaser!
```
> deps: update goreleaser/goreleaser-action action to v6

- internal/cmd/config/add.go
- internal/cmd/config/add_test.go
- internal/cmd/util/util.go
- internal/cmd/util/util_test.go
- internal/state/config/options.go
Originally, options with a slice value were treated as sets instead of lists. This was because options like `default-ssh-keys` do not care about the order of keys. However, the order for example is important for the default sort column options, so it needs to be preserved. This PR fixes this.
> fix(config): ordering of list option values not preserved

- internal/state/state.go
The hcloud client option name was using the retry back off option instead of the poll back off option.
> fix: ineffective poll interval option

- internal/cmd/server/create.go
- internal/cmd/server/create_test.go
Closes #820
Also add some more data in the mocked server calls to cover more code.
> fix: printing for server create with mulitple networks

- go.mod
- go.sum
- internal/cmd/loadbalancertype/describe.go
- internal/cmd/loadbalancertype/describe_test.go
- internal/cmd/servertype/describe.go
- internal/cmd/servertype/describe_test.go
- internal/cmd/servertype/list.go
- internal/cmd/servertype/list_test.go
The API has been updated to provide a better insight and more flexibility for displaying the pricing of traffic for servers and load balancers.
In addition to the new fields, the old fields are deprecated and will be set to `null` in the API on 2024-08-05.
In the CLI this mostly affects the `hcloud server-type list` command, where we have previously shown a column `traffic`. This is no longer possible, because there is no single included traffic for a server type, and instead this depends on the location. We have set the field to `-`  and removed it from the default columns. The information is still available in `hcloud server-type describe <server-type-name>`, now in the "Pricing" section of the output.
This also affects the JSON and YAML output of both `hcloud server-type list` and …
> feat: new APIs for traffic pricings 

- internal/cmd/datacenter/describe.go
- internal/cmd/datacenter/describe_test.go
> feat: improve datacenter describe server types readability

- go.mod
Drop support for go 1.21 (we already build with go 1.23).
> feat: drop support for go 1.21

- internal/cmd/util/util.go
- internal/cmd/util/util_test.go
Display a dollar sign when the currency is USD.
> fix: display $ when the currency is USD

- internal/cmd/firewall/delete_rule.go
- internal/cmd/firewall/validation.go
- internal/cmd/firewall/validation_test.go
We now ignore firewall rule description when searching a rule to delete in the existing rules.
This allows the users to delete a rule without having to pass the description of the rule.
> fix: ignore firewall rule description when looking for a rule to delete

- internal/cmd/firewall/delete_rule.go
- internal/cmd/firewall/validation.go
- internal/cmd/firewall/validation_test.go
This reverts commit 4535f26bad3436248585cea4fbec90a5262a20f6 (#961)
Two firewall rules with only a different description does not raise any validation error in the backend. Therefor, we must be able to target duplicate rules with different descriptions. Users must provide the description to be able to delete a rule.
> revert: fix: ignore firewall rule description when looking for a rule to delete

- internal/cmd/base/describe.go
- internal/cmd/base/describe_test.go
- internal/cmd/certificate/describe.go
- internal/cmd/datacenter/describe.go
- internal/cmd/firewall/describe.go
- internal/cmd/floatingip/describe.go
- internal/cmd/image/describe.go
- internal/cmd/iso/describe.go
- internal/cmd/loadbalancer/describe.go
- internal/cmd/loadbalancertype/describe.go
- internal/cmd/location/describe.go
- internal/cmd/network/describe.go
- internal/cmd/placementgroup/describe.go
- internal/cmd/primaryip/describe.go
- internal/cmd/server/describe.go
- internal/cmd/servertype/describe.go
- internal/cmd/sshkey/describe.go
- internal/cmd/volume/describe.go
> refactor: make base describe command generic

- internal/cmd/base/describe.go
- internal/cmd/certificate/describe.go
- internal/cmd/datacenter/describe.go
- internal/cmd/firewall/describe.go
- internal/cmd/floatingip/describe.go
- internal/cmd/image/describe.go
- internal/cmd/iso/describe.go
- internal/cmd/loadbalancer/describe.go
- internal/cmd/loadbalancertype/describe.go
- internal/cmd/location/describe.go
- internal/cmd/network/describe.go
- internal/cmd/placementgroup/describe.go
- internal/cmd/primaryip/describe.go
- internal/cmd/server/describe.go
- internal/cmd/servertype/describe.go
- internal/cmd/sshkey/describe.go
- internal/cmd/volume/describe.go
The JSON keys became unused in #650.
> refactor: remove unused constants in describe commands

- internal/cmd/firewall/add_rule.go
- internal/cmd/firewall/add_rule_test.go
- internal/cmd/firewall/delete_rule.go
- internal/cmd/firewall/delete_rule_test.go
Three flags were not correctly split up when the user specified multiple values separated by comma. This happened because the `StringArray` flag explitely does not split the input. `StringSlice`, which we use nearly everywhere else, does split input by comma.
Fixes #986
> fix: some list flags are not correctly parsed

- internal/cmd/cmpl/suggestions.go
- internal/cmd/cmpl/suggestions_test.go
Makes the code more readable by giving a keyword to the recurring type.
(Same as #994, but using the type introduced in upstream Cobra)
> refactor: use cobra.CompletionFunc type

- internal/cmd/all/list_test.go
- internal/cmd/base/list_test.go
- internal/cmd/config/list_test.go
- internal/cmd/context/list_test.go
- internal/cmd/datacenter/list_test.go
- internal/cmd/firewall/list_test.go
- internal/cmd/image/list_test.go
- internal/cmd/iso/list_test.go
- internal/cmd/loadbalancertype/list_test.go
- internal/cmd/location/list_test.go
- internal/cmd/output/output.go
- internal/cmd/output/output_test.go
- internal/cmd/servertype/list_test.go
- internal/cmd/sshkey/list_test.go
- internal/cmd/volume/list_test.go
- internal/testutil/cmd.go
- test/e2e/certificate_test.go
- test/e2e/datacenter_test.go
- test/e2e/floatingip_test.go
- test/e2e/iso_test.go
- test/e2e/load_balancer_type_test.go
- test/e2e/network_test.go
- test/e2e/placement_group_test.go
- test/e2e/sshkey_test.go
- test/e2e/util.go
The previously used `text/tabwriter` does not even attempt to handle Unicode characters that may have a default width != 0. This causes issues in tables where any column has such a Unicode character (like emojis), as the alignment for that row would be broken.
We already use the new package for generating our docs, so this "only" moves it from tools to production dependency.
I tried to copy the previous style as much as possible and left the surrounding code as is. There is some potential for simplification because the new package can handle a lot of the column/view logic for us.
> refactor: tablewriter that can handle unicode

- .goreleaser.yml
https://goreleaser.com/deprecations/#archivesformat
> chore: update deprecated goreleaser config
