cli.go
floatingip_create.go
floatingip_describe.go
root.go
server_create.go
server_describe.go
sshkey_create.go
sshkey_describe.go

We first need to discuss how we want to allow the user to configure
how output should be formattet (table, JSON, YAML, etc.).

Remove JSON output

---

completion.go
location.go
location_describe.go
location_list.go
root.go

Add location list and describe commands

---

completion.go
iso.go
iso_describe.go
iso_list.go
root.go
server.go
server_attach_iso.go
server_detach_iso.go

Closes #17 
Closes #14 
Closes #15 
Closes #16

Iso commands

---

completion.go
server.go
server_update.go

Implement server update command

---

.travis.yml
script/variants.txt

Test it builds on all OS/arch variants

---

completion.go
image.go
image_update.go

Add image update command

---

completion.go
server.go
server_change_type.go

Add server change-type command

---

completion.go
floatingip.go
floatingip_assign.go
floatingip_create.go
floatingip_update.go

Add floatingip update command (#7)

---

completion.go
server.go
server_disable_backup.go
server_enable_backup.go

Implement server backup commands (#10,#11)

---

completion.go
context.go
context_use.go
datacenter_describe.go
floatingip_describe.go
server_create.go
server_enable_rescue.go

Add missing completions

---

server_describe.go

Fix alignment of Floating IP section

---

floatingip_create.go

Fix location/server validation

---

floatingip_describe.go
floatingip_list.go
server_describe.go
server_list.go

Add subnet to ipv6 ips and show server ipv6 address

---

server_update.go

Check if there are any updates

---

README.md
context_create.go

Auto-activate first context created

---

sshkey_delete.go
sshkey_describe.go

Support describing/deleting SSH key by name

---

.gitignore
.travis.yml
script/build.bash
script/git-version.bash
test/version.bats
version.go

Build release using:
```shell
./script/build.bash linux amd64 `./script/git-version.bash`
```

Set cli version on compile

---

script/package.bash

Convert LF to CRLF for Windows

---

script/build.bash

Fix setting Version via -ldflags

---

CHANGES.md
context_create.go

Auto-activate created context

---

floatingip_create.go

Show available Floating IP types in usage

---

CHANGES.md
context_create.go

Do not echo token when creating a context

---

CHANGES.md
Gopkg.lock
Gopkg.toml
server_create.go
vendor/github.com/hetznercloud/hcloud-go/CHANGES.md
vendor/github.com/hetznercloud/hcloud-go/hcloud/client.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/hcloud.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/server.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/server.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/server_test.go

Add --user-data-from-file flag to server create command

---

README.md

Mention Arch Linux package in README

---

CHANGES.md
cli.go
context_list.go
datacenter_list.go
floatingip_list.go
image_list.go
iso_list.go
location_list.go
output.go
output_test.go
root.go
server_list.go
servertypes_list.go
sshkey_list.go
util.go

Add output documentation

---

CHANGES.md
cli/server.go
cli/server_ssh.go

Add command to spawn an SSH connection to the server

---

CHANGES.md
Gopkg.lock
cli/cli.go
cli/root.go
vendor/github.com/hetznercloud/hcloud-go/CHANGES.md
vendor/github.com/hetznercloud/hcloud-go/hcloud/action.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/action_test.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/client.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/client_test.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/datacenter_test.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/error.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/floating_ip.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/floating_ip_test.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/hcloud.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/image.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/image_test.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/iso.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/iso_test.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/location_test.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/schema.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/image.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/iso.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/server.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/server_type.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/schema_test.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/server.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/server_test.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/server_type.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/server_type_test.go
vendor/github.com/hetznercloud/hcloud-go/hcloud/ssh_key_test.go

Resubmit of #118 for a clean git history.

add polling interval option

---

CHANGES.md
cli/image_list.go

This PR adds a little flag to the images list command for easily filtering the list based on the type

Add filter for images (#65)

---

README.md

Signed-off-by: Gerardo Di Iorio <arete74@gmail.com>

Add Void Linux install instruction

---

CHANGES.md
cli/volume_create.go

When you want to create a volume with the server name given, this would not work.
This PR fix the error.

Fix volume creation when only server name is given.

---

CHANGES.md
cli/completion.go
cli/server_enable_backup.go

Deprecate `--window` flag on `hcloud server enable-backup`

---

cli/cli.go
cli/server_create.go
cli/util.go
cli/volume_create.go
go.mod
go.sum

Update hcloud-go to v1.11.0
Wait for the new next actions on server create and volume create

Wait Next Actions

---

CHANGES.md
cli/server_create.go
cli/volume_attach.go
cli/volume_create.go
go.mod
go.sum

This PR adds automount and format support for volumes.

Add automount and format support for volumes

---

CHANGES.md
cli/server_ssh.go

Allow commands to be sent through "hcloud server ssh"

---

CHANGES.md
README.md
cli/context_list.go
cli/datacenter_describe.go
cli/datacenter_list.go
cli/floatingip_describe.go
cli/floatingip_list.go
cli/image_describe.go
cli/image_list.go
cli/iso_describe.go
cli/iso_list.go
cli/location_describe.go
cli/location_list.go
cli/output.go
cli/output_test.go
cli/server_describe.go
cli/server_list.go
cli/servertypes_describe.go
cli/servertypes_list.go
cli/sshkey_describe.go
cli/sshkey_list.go
cli/util.go
cli/volume_describe.go
cli/volume_list.go

Add support for JSON and template output

---

CHANGES.md
cli/cli.go
cli/floatingip_list.go
cli/image_list.go
cli/volume_list.go

Unify Server Information on List Outputs

---

cli/server_create_image.go

Remove unused default value of hcloud server create-image type flag

---

CHANGES.md
cli/server.go
cli/server_ip.go

Add hcloud server ip command

---

CHANGES.md
cli/floatingip_add_label.go
cli/floatingip_assign.go
cli/floatingip_delete.go
cli/floatingip_describe.go
cli/floatingip_remove_label.go
cli/floatingip_set_rdns.go
cli/floatingip_unassign.go
cli/floatingip_update.go
cli/image_describe.go
cli/sshkey_describe.go
cli/volume_describe.go
go.mod
go.sum

Update hcloud-go to 1.17.0
Expose `Created` on `hcloud floating-ip|image|ssh-key|volume describe`

Expose Created on several describe commands

---

.github/workflows/bot_stale.yml

Add stale bot

---

cli/server_list.go

Bugfix: Add private_net to server list json response

---

cli/server_list.go

Add missing labels to hcloud server list -o json response

---

cli/certificate_create.go
cli/floatingip_create.go
cli/floatingip_set_rdns.go
cli/load_balancer_add_service.go
cli/load_balancer_attach_to_network.go
cli/load_balancer_create.go
cli/load_balancer_delete_service.go
cli/load_balancer_detach_from_network.go
cli/load_balancer_update_service.go
cli/network_add_route.go
cli/network_change_ip_range.go
cli/network_create.go
cli/network_remove_route.go
cli/network_remove_subnet.go
cli/server_attach_to_network.go
cli/server_change_alias_ips.go
cli/server_create.go
cli/server_create_image.go
cli/server_detach_from_network.go
cli/server_rebuild.go
cli/server_set_rdns.go
cli/sshkey_create.go
cli/volume_attach.go
cli/volume_create.go
cli/volume_resize.go

Add (required) to help text of all required flags

---

cli/server_describe.go
cli/server_list.go
go.mod
go.sum

Update hcloud-go to 1.22.0 and expose correct disk size for resized without disk server

---

cli/server_create.go

Fix server creation --image was not used correctly

---

cli/load_balancer.go
cli/load_balancer_metrics.go
cli/server.go
cli/server_metrics.go
go.mod
go.sum

This is WIP, as long as the hcloud-go wasn't released

Implement metrics commands for servers and load-balancers

---

cli/image_describe.go
cli/image_list.go
cli/server_describe.go

Unify Image Size with Cloud Console (2 digits after decimal point)

---

internal/cmd/server/create.go

Allow creation of servers with firewalls

---

README.md

See #299, too for further information.

Added installation instructions for Windows via Scoop.

---

internal/cmd/output/output.go

Fix output option broke with last release

---

internal/cmd/firewall/list.go

Support getting Firewalls by label selector

---

go.mod
go.sum
internal/cmd/firewall/apply_to_resource.go
internal/cmd/firewall/describe.go
internal/cmd/firewall/list.go
internal/cmd/firewall/remove_from_resource.go

Implement Firewall resource label selector

---

go.mod
go.sum
internal/cmd/firewall/add_rule.go
internal/cmd/firewall/delete_rule.go

Add Support for Firewall Protocol GRE & ESP

---

cmd/hcloud/main.go
internal/cli/root.go
internal/cmd/certificate/describe.go
internal/cmd/datacenter/datacenter.go
internal/cmd/datacenter/describe.go
internal/cmd/datacenter/list.go
internal/hcapi2/client.go
internal/hcapi2/server_type.go
internal/hcapi2/zz_server_type_client_mock.go

Move datacenter commands to new structure

---

internal/cmd/base/delete.go
internal/cmd/base/update.go
internal/cmd/certificate/certificate.go
internal/cmd/certificate/update.go
internal/cmd/firewall/firewall.go
internal/cmd/firewall/update.go
internal/cmd/floatingip/floatingip.go
internal/cmd/floatingip/update.go
internal/cmd/image/image.go
internal/cmd/image/update.go
internal/cmd/loadbalancer/load_balancer.go
internal/cmd/loadbalancer/update.go
internal/cmd/network/network.go
internal/cmd/network/update.go
internal/cmd/server/server.go
internal/cmd/server/update.go
internal/cmd/sshkey/sshkey.go
internal/cmd/sshkey/update.go
internal/cmd/volume/update.go
internal/cmd/volume/volume.go

Migrate Update Commands to new structure

---

go.mod
go.sum
internal/cmd/image/list.go

Add support for App images

---

internal/cmd/firewall/list.go
internal/cmd/sshkey/list.go
internal/cmd/volume/list.go

- firewall list
- ssh-key list
- volume list
Fixes #346 

Fix pagination of list commands

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/release_on_tag.yml
.gitlab-ci.yml
go.mod
internal/state/config_unix.go
internal/state/config_windows.go
tools.go

Use go 1.17 for tests & builds

---

go.mod
go.sum
internal/cmd/loadbalancer/describe.go
internal/cmd/loadbalancer/load_balancer.go
internal/cmd/loadbalancer/set_rdns.go

Add support for LB DNS PTRs

---

internal/cmd/datacenter/list.go
internal/cmd/iso/list.go
internal/cmd/location/list.go

Fix panic on iso & location list as json

---

internal/cmd/image/list.go

Fix filtering image list by type

---

internal/cmd/server/describe.go

Fix missing new line on hcloud describe command

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/release_on_tag.yml
.gitlab-ci.yml

Use Go 1.18 for building & testing

---

internal/cmd/output/output.go

Fixes https://github.com/hetznercloud/cli/issues/374

Trim and lowercase for column selectors 

---

.github/workflows/release_on_tag.yml

Update Gon to 0.2.5

---

go.mod
go.sum
internal/cmd/base/list.go
internal/cmd/certificate/list.go
internal/cmd/datacenter/list.go
internal/cmd/firewall/list.go
internal/cmd/floatingip/list.go
internal/cmd/image/list.go
internal/cmd/iso/list.go
internal/cmd/loadbalancer/list.go
internal/cmd/loadbalancertype/list.go
internal/cmd/location/list.go
internal/cmd/network/list.go
internal/cmd/network/list_test.go
internal/cmd/placementgroup/list.go
internal/cmd/placementgroup/list_test.go
internal/cmd/server/list.go
internal/cmd/servertype/list.go
internal/cmd/sshkey/list.go
internal/cmd/volume/list.go

Allow to sort the response of all resources by using --sort

---

internal/cmd/server/ssh.go

Fix hcloud server ssh with flexible network options

---

internal/cmd/floatingip/set_rdns.go
internal/cmd/loadbalancer/set_rdns.go
internal/cmd/primaryip/assign.go
internal/cmd/primaryip/changedns.go
internal/cmd/primaryip/disable_protection.go
internal/cmd/primaryip/enable_protection.go
internal/cmd/primaryip/list.go
internal/cmd/primaryip/unassign.go
internal/cmd/server/set_rdns.go
internal/hcapi2/primaryip.go
internal/hcapi2/zz_certificate_client_base.go
internal/hcapi2/zz_datacenter_client_base.go
internal/hcapi2/zz_firewall_client_base.go
internal/hcapi2/zz_floating_ip_client_base.go
internal/hcapi2/zz_image_client_base.go
internal/hcapi2/zz_iso_client_base.go
internal/hcapi2/zz_loadbalancer_client_base.go
internal/hcapi2/zz_loadbalancer_type_client_base.go
internal/hcapi2/zz_location_client_base.go
internal/hcapi2/zz_network_client_base.go
internal/hcapi2/zz_placement_group_client_base.go
internal/hcapi2/zz_primary_ip_client_base.go
internal/hcapi2/zz_rdns_client_base.go
internal/hcapi2/zz_server_client_base.go
internal/hcapi2/zz_server_type_client_base.go
internal/hcapi2/zz_ssh_key_client_base.go
internal/hcapi2/zz_volume_client_base.go

Closes https://github.com/hetznercloud/cli/issues/401

Fix primary-ip list  -o json

---

internal/cmd/servertype/describe.go

Closes https://github.com/hetznercloud/cli/issues/405

Fix hcloud server-type describe completion

---

internal/cmd/server/list.go
internal/cmd/util/util.go

Signed-off-by: Tom Siewert <tom.siewert@hetzner.com>

server/list: Add missing PlacementGroup to JSON

---

internal/cmd/server/rebuild.go

Related to hetznercloud/hcloud-go#244

feat(server): return password on rebuild

---

internal/cmd/placementgroup/describe.go

fix(placement-group): invalid json response #464

---

.gitlab-ci.yml

- Remove breaking GO* env variables
- Remove dependency on internal repositories, as they are not working for us

test: fix gitlab test setup

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/release_on_tag.yml
.gitlab-ci.yml
go.mod

Go 1.18 has been EOL for some time

chore: test & build with Go 1.20

---

.github/CODEOWNERS
.gitlab/CODEOWNERS

This will automatically request reviews from the right people.

chore: add CODEOWNERS

---

.goreleaser.yml

fix(build): ensure signature is properly generated

---

internal/cmd/floatingip/disable_protection.go
internal/cmd/floatingip/enable_protection.go
internal/cmd/image/disable_protection.go
internal/cmd/image/enable_protection.go
internal/cmd/loadbalancer/disable_protection.go
internal/cmd/loadbalancer/enable_protection.go
internal/cmd/network/disable_protection.go
internal/cmd/network/enable_protection.go
internal/cmd/primaryip/disable_protecion_test.go
internal/cmd/primaryip/disable_protection.go
internal/cmd/primaryip/enable_protecion_test.go
internal/cmd/primaryip/enable_protection.go
internal/cmd/server/disable_protection.go
internal/cmd/server/enable_protection.go
internal/cmd/volume/disable_protection.go
internal/cmd/volume/enable_protection.go

In preparation for the changes requested in #488

refactor: extract protection level parsing and changing

---

internal/cmd/server/create.go

feat(server): add --enable-backup flag to "create" command

---

internal/cmd/context/active.go
internal/cmd/context/delete.go
internal/cmd/context/use.go

feat: add warning messages to context commands

---

.github/release-please-config.json
.github/workflows/release-please.yml

This reverts commit 1b4a2372109707b92c068d60c65939757a78bad7.

deps: revert update google-github-actions/release-please-action action to v4 (#620)

---

internal/cmd/loadbalancer/metrics.go
internal/cmd/server/metrics.go

fix: wording when metrics are not yet available

---

internal/cmd/loadbalancer/metrics.go
internal/cmd/server/metrics.go

fix: allow multiple --type flags for metrics commands

---

.github/workflows/build.yml
.github/workflows/release.yml
.gitlab-ci.yml

Remove the download logs from the actually tool run output.

ci: download go tools before running them

---

.github/workflows/releaser-pleaser.yaml

The job currently fails, bug is fixed in new releaser-pleaser version.

deps: update releaser-pleaser to v0.4.2
